### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by grafst** [lauro-cesar/connectivity_wall#1]
Hi
Im using your connectivity_wall package for my app. I think it would exactly do what I need. However it doesn't seem to work....

some details:
onPingUrl: "http://192.168.1.49/status"
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (13 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

stacktrace:

dart-sdk/lib/async/future_impl.dart 864:18                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback
Error: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/async/future_impl.dart 181:7                                     handleError
dart-sdk/lib/async/future_impl.dart 778:46                                    handleError
dart-sdk/lib/async/future_impl.dart 799:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 873:16                                    <fn>
dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>

sorry, i'm really new to stacktraces. tell me if you need more infos...

**Comment by lauro-cesar** [comment]
Hi.

The onPingUrl accept only Uri type.

Try:  onPingUrl: Uri.parse("http://192.168.1.49/status"),


Please, provide more details of the usage, like so:

```
ConnectivityWall(
  onDisconnectedWall: const OffLineWall(),
  onConnectivityChanged: (results) {},
  onDisconnected: () {
    if (kDebugMode) {
      print("offline");
    }
  },
  onPingUrl: Uri.parse(AppConstants.pingUrl),
  onPingResponse: (statusCode) {
    if (kDebugMode) {
      print(statusCode);
    }
  },
  responseCode: const [200, 404],
  pingInterval: 300,
  onConnectedWall: const AutoLoginProvider()
)
```

Thank you

**Comment by lauro-cesar** [comment]
Hi, thank you for your time on letting me know about this possible bug.

I need  more details.

Could you please show me the code where you instantiate the widget?

Thanks.

**Comment by lauro-cesar** [comment]
Closing this issue, since the error it is not related to ConnectivityWall.

This error probably comes from the wrong definition of FlutterError.onError,

The right way:

```dart
FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
};
```
